version: "3.1"
services:

    mysql:
      platform: linux/x86_64
      image: mysql:5.7
      container_name: teresa-mysql
      working_dir: /application
      command: mysqld --sql_mode="IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
      volumes:
        - .:/application
        - ./db:/var/lib/mysql
        - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_DATABASE=teresa
        - MYSQL_USER=teresa
        - MYSQL_PASSWORD=heslo
      ports:
        - "8891:3306"

    webserver:
      #image: nginx:alpine
      build: ./docker/nginx/
      container_name: teresa-nginx
      working_dir: /application
      volumes:
          - ../:/application
          - ./log/nginx:/var/log/nginx
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
          - "8818:80"
      links:
          - mysql:mysql.local

    php-fpm:
      platform: linux/x86_64
      build: docker/php-fpm
      container_name: teresa-php-fpm
      working_dir: /application
      volumes:
        - ../:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
      links:
          - mysql:mysql.local

    adminer:
      container_name: teresa-adminer
      image: adminer
      ports:
        - 8080:8080
